<?php
/**
 * Stovpak_Article extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Stovpak
 * @package        Stovpak_Article
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article view widget template
 *
 * @category    Stovpak
 * @package     Stovpak_Article
 * @author      Ultimate Module Creator
 */
?>
<?php $_article = $this->getCurrentArticle();?>
<?php if ($_article) :?>
    <div class="article-widget-view">
        <h3><?php echo $_article->getTitle()?></h3>
        <div>
            <div class="title-widget">
                <?php echo Mage::helper('stovpak_article')->__('Title');?>:<?php echo $_article->getTitle();?>
            </div>
            <div class="abstract-widget">
                <?php echo Mage::helper('stovpak_article')->__('Abstract');?>:<?php echo $_article->getAbstract();?>
            </div>
            <div class="body-widget">
                <?php echo Mage::helper('stovpak_article')->__('Body');?>:<?php echo $_article->getBody();?>
            </div>
            <div class="image-widget">
                <?php if ($_article->getImage()) :?>
    <img src="<?php echo Mage::helper('stovpak_article/article_image')->init($_article, 'image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_article->getTitle());?>" />
<?php endif;?>
            </div>

        </div>
    </div>
<?php endif;?>
