<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */?>

 <div class="color-pallets">
          <div class="color-item">
            <a href="#" style="background: #DEE2E1;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #FFFFFF;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F2F0EB;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #EFEAD7;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F0EADA;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F0E2C7;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #EDDCC9;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #DFD1BB;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #DCD7D4;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C8CACC;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C7C0B5;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BBB1A8;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B6AEA5;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BAA38B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A49C8E;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #918C86;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #958D84;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C1A68D;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D5BA98;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #DBD8E1;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BDBEBF;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B0B7BE;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9A9B98;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #8B8E8D;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #818387;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #595E62;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #515244;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #403935;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #2C2F32;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #7A726F;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #594440;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #493B39;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #564235;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #765446;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #60413A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #855E4B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #714C30;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #916B53;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9B836C;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #AF9E89;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #916F3B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BC9C69;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D5A372;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D1B893;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #E4C289;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #DBCBAA;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F9E18E;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F1DE9C;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #FCDB95;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #FAC668;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #FFC007;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #FFBE79;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B0583A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C7622B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #DC793D;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D3833D;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BD7B27;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #CA7A42;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A96D35;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B05846;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B0654B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #FFC7B6;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F0C7C1;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #ED5656;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D85863;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F6D6D8;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #F5BFCC;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #EB81A2;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #EC5D73;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BB466F;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #CF86A3;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C7458B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A85387;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C46858;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B0583A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A05747;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #5C343F;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #5D303A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #933D3A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #852839;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A22E37;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C81D31;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D12631;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BC2A3A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D6394B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9B2242;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9F4576;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BD97CB;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9B90C8;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #706A99;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #63385E;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #6E5862;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #8A6B76;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B7A9AD;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C1A4B4;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9F9AAE;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #ACA8C7;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C3D7EE;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #89ABE3;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #8691B7;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #5C6476;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #2C3540;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #3C434E;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #13294B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #527183;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #5A7CC2;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #3a5b8d;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #155DA4;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #465FAD;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #6CA0DC;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #6386BF;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #96B3D1;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #869BAD;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A4B7C8;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BFCFDD;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D7E4E2;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B5D2DC;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9BC1CC;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #92B5D9;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #006A8C;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #007591;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #006578;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #00A4B4;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #ACD3DE;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #9ECBC8;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #5AD0BA;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C0D8BE;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BFEADA;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #88DDBF;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #3D9F88;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #00A68C;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #4C8087;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #007173;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #8A9C9C;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #6D8181;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #005960;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C5E0D5;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B1CBBA;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #CFD8C7;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #768984;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #83A393;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #889C8F;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B2BAB6;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B1AC85;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #97917D;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #8E9C4B;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B4BD86;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #B0B583;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #7D876E;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #A5CA77;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #749862;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #6D9654;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #428065;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #2C504A;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #5C6D61;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #676B57;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #C5BA7F;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #DFD34F;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #E4BB25;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #BDA11E;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #AD9742;"></a>
          </div>
          <div class="color-item">
            <a href="#" style="background: #D3C54D;"></a>
          </div>
        </div>
        <div class="header-top-panel clr">
          <div class="header-top-col basket mobile">
            <a href="#">(2)</a>
          </div>
          <div class="header-top-col signup">
            <a onclick="OpenPopup('popup-sign-up-emails')"><span class="mobile-inline">Join</span><span class="screen-inline">Sign UP for emails</span></a>
          </div>
          <div class="header-top-col my-favorite">
            <a href="#">(4)</a>
          </div>
          <div class="header-top-col my-account">
            <a href="#">My Account</a>
            <ul class="header-top-col-subnav">
              <li>
                <a href="#">Account Dashboard</a>
              </li>
              <li>
                <a href="#">Account Info</a>
              </li>
              <li>
                <a href="#">My Studio</a>
              </li>
              <li>
                <a href="#">Orders</a>
              </li>
              <li>
                <a href="#">Address Book</a>
              </li>
              <li>
                <a href="#">Email Subscriptions</a>
              </li>
            </ul>
          </div>
          <div class="header-top-col my-signout">
            <a class="username screen-inline" href="#">Welcome Marilyn</a><a class="signout" href="#">Sign Out</a>
          </div>
          <a class="design-link screen-inline" href="#">VISIT BEACON HILL</a>
        </div>
        <div class="shop-palette-link">
          Search by Color
        </div>
        <div class="scroll-palette-title">
          Scroll
        </div>
        <div class="color-palette-title">
          <a href="shop-by-color.html">Create a<br>Color Palette</a>
        </div>
        <a class="mobile-nav-toggle mobile" href="#"><i></i><i></i><i></i><span>menu</span></a>