<?php
/**
 * Stovpak_Article extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Stovpak
 * @package        Stovpak_Article
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article view template
 *
 * @category    Stovpak
 * @package     Stovpak_Article
 * @author      Ultimate Module Creator
 */
?>


<?php $_article = $this->getCurrentArticle();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="blog-page default-page clearfix">
    <div class="container">
        <div class="row">

            <div class="col-lg-9 col-md-8 col-sm-12 ">
            <div class="blog-page-single clearfix">
              <article id="post-2" class="post-2 page type-page status-publish hentry  clearfix">
                <div class="page-contents">
                    <div class="article-image">
                        <?php if ($_article->getImage()) :?>
                                <img src="<?php echo Mage::helper('stovpak_article/article_image')->init($_article, 'image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_article->getTitle());?>" />
                        <?php endif;?>
                    </div>
                    <header class="entry-header">
                        <div class="entry-meta hhidden">
                          <h2 class="entry-title"><?php echo $_article->getTitle(); ?></h2>
                          <time class="updated" datetime="<?php echo $_article->getUpdated_at();?>">
                              <?php echo $this->__(date('d m Y',strtotime($_article->getUpdated_at()))); ?>
                          </time>
                        </div>
                    </header>
                    
                    <div class="entry-content">
                       <?php echo $_article->getBody();?>
                    </div>
                </div>
              </article>
            </div>

            
            </div>

            <div class="col-lg-3 col-md-4 col-sm-12 ">
                <aside class="sidebar clearfix">
                    <section id="categories-3" class="widget widget_categories">
                       
                    </section>
                </aside>            
            </div>

        </div>
    </div>
</div>



